function printInfo(sessionID)

start_time = clock;
timestr = [num2str(start_time(4), '%02d'), ':' num2str(start_time(5), '%02d'), ...
       ':' num2str(round(start_time(6)), '%02d')];
fprintf(['\n', ...
'                           - ' timestr,  ' -\n', ...
'------------------------------------------------------------------------- \n', ...
' Initialising registration of images for session: ', sessionID, '\n', ...
'------------------------------------------------------------------------- \n', ...
          '\n' ])
      
end
